# Site settings
title: site.title
description: site.description
email: site.email

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://termsuite.github.io" # the base hostname & protocol for your site
github_username:  termsuite
github: https://github.com/termsuite/termsuite-core
permalink: none
exclude: ['deploy.sh', 'Gemfile.lock', 'Gemfile']
bintray: https://bintray.com/termsuite/generic/termsuite-ui

termsuite:
  ui:
    bintray: https://dl.bintray.com/termsuite/generic/3.0.8/
    windows: "win32.win23.x86_64.zip"
    linux: "linux.gtk.x86_64.tar.gz"
    macos: "macosx.cocoa.x86_64.tar.gz"
  maven: http://search.maven.org/remotecontent?filepath=fr/univ-nantes/termsuite/termsuite-core/
  version: "3.0.8"

resources:
  jar: https://bintray.com/termsuite/generic/download_file?file_path=termsuite-resources.jar
  filename: termsuite-resources.jar

dicos:
  zip: https://bintray.com/termsuite/generic/download_file?file_path=dictionaries-free.zip
  filename: dictionaries-free.zip

corpus:
  we: https://bintray.com/termsuite/generic/download_file?file_path=wind-energy.zip
  mobile: https://bintray.com/termsuite/generic/download_file?file_path=mobile-technology.zip

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  parse_block_html: true

gems:
  - jekyll-redirect-from

collections:
  documentation:
    output: true
    permalink: /documentation/:path/

languages: ["en", "fr"]
exclude_from_localizations: ["fonts", "js", "img", "css"]
