# Site settings
title: site.title
description: site.description
email: site.email

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://termsuite.github.io" # the base hostname & protocol for your site
github_username:  termsuite
github: https://github.com/termsuite/termsuite-core
permalink: none
exclude: ['deploy.sh', 'Gemfile.lock', 'Gemfile']

termsuite:
  ui:
    filex: http://filex.univ-nantes.fr/get?k=S5iO0LSGt4dO0TbNxnV 
  maven: http://search.maven.org/remotecontent?filepath=fr/univ-nantes/termsuite/termsuite-core/
  snapshot: https://oss.sonatype.org/content/repositories/snapshots/fr/univ-nantes/termsuite/termsuite-core/2.1-SNAPSHOT/
  version: "2.0"

resources:
  jar: https://logiciels.lina.univ-nantes.fr/redmine/attachments/download/562/termsuite-resources.jar
  filename: termsuite-resources.jar

dicos:
  zip: https://logiciels.lina.univ-nantes.fr/redmine/attachments/download/128/BilingualDicosForTermSuiteAligner.zip
  filename: BilingualDicosForTermSuiteAligner.zip

corpus:
  we: http://www.lina.univ-nantes.fr/taln/maven/wind-energy.tgz
  mobile: http://www.lina.univ-nantes.fr/taln/maven/mobile-technology.tar.gz

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  parse_block_html: true

collections:
  documentation:
    output: true
    permalink: /documentation/:path/

languages: ["en", "fr"]
exclude_from_localizations: ["fonts", "js", "img", "css"]
